services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile.dev
    working_dir: /workspace
    command: sh -c "pnpm install && pnpm dev --hostname 0.0.0.0 --port 3000"
    volumes:
      - ./:/workspace
      - frontend-node-modules:/workspace/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile.dev
    working_dir: /workspace
    command: >-
      sh -c "cd python_backend &&
             uv sync --frozen --no-dev &&
             uv run main.py dev"
    volumes:
      - ./python_backend:/workspace
      - backend-uv-cache:/root/.cache/uv
    env_file:
      - .env
    environment:
      UV_PROJECT_ENVIRONMENT: /workspace/.venv
      LOG_LEVEL: INFO

volumes:
  frontend-node-modules:
  backend-uv-cache:
