# GitHub Actions template for future Docker Compose automation.
# The job is intentionally commented out until deployment targets are defined.

name: compose-preview

on:
  workflow_dispatch:
    inputs:
      notes:
        description: "Optional notes for this manual run"
        required: false

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #
  #     - name: Log in to GitHub Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #
  #     - name: Build images defined in docker-compose.yml
  #       run: docker compose build
  #
  #     - name: Run services for smoke tests (optional)
  #       run: docker compose up --abort-on-container-exit --exit-code-from backend
  #
  #     - name: Tear down
  #       if: always()
  #       run: docker compose down --volumes --remove-orphans
